# Change these first
owner: pyleglise # Your GitHub organization or username, where this repository lives
repo: upptimeMonitor # The name of this repository

# Configuration des intervalles de surveillance
schedules:
  uptime: "*/5 * * * *"      # Toutes les 5 minutes
  graphs: "*/5 * * * *"       # Toutes les 5 minutes  
  summary: "*/5 * * * *"      # Toutes les 5 minutes

sites:
  - name: axialdata
    url: https://www.axialdata.net/presentation
    check: "keyword"
    keyword: "A propos de axialdata"
  - name: CFF to PDF API via Fly.io
    url: https://cff-to-pdf-api.fly.dev/api/v2/webhook/connect
    check: "keyword"
    keyword: "Authorized users only"
  - name: Claire Debourg Arbitration
    url: https://www.cdarbitration.com
  - name: Vitrail Martinique
    url: https://www.vitrailmartinique.com
  - name: Ma Pause Mieux Etre
    url: https://www.mapausemieuxetre.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptimeMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Moniteur de Statut"
  introTitle: "**Surveillance axialdata**"
  introMessage: "Surveillance en temps réel des services de axialdata"
  navbar:
    - title: Status
      href: /upptimeMonitor/
    - title: Force Check
      href: https://github.com/$OWNER/$REPO/actions/workflows/uptime.yml
    - title: axialdata
      href: https://www.axialdata.net
  # Ajout d'un script personnalisé pour afficher les heures de vérification
  customCSS: |
    .check-times {
      background: #f8f9fa;
      border: 1px solid #dee2e6;
      border-radius: 8px;
      padding: 15px;
      margin: 20px 0;
      text-align: center;
    }
    .check-times h3 {
      margin: 0 0 10px 0;
      color: #495057;
    }
    .check-times p {
      margin: 5px 0;
      font-size: 14px;
    }
  customJS: |
    function createCheckTimesWidget() {
      // Créer le widget s'il n'existe pas déjà
      if (!document.getElementById('check-times-widget')) {
        const widget = document.createElement('div');
        widget.id = 'check-times-widget';
        widget.className = 'check-times';
        widget.innerHTML = `
          <h3>🕐 Horaires de vérification</h3>
          <p><strong>Dernière vérification :</strong> <span id="last-check">Calcul en cours...</span></p>
          <p><strong>Prochaine vérification :</strong> <span id="next-check">Calcul en cours...</span></p>
        `;
        
        // Essayer plusieurs sélecteurs pour trouver le bon conteneur
        let container = document.querySelector('main') || 
                       document.querySelector('.container') || 
                       document.querySelector('#content') ||
                       document.querySelector('body');
        
        if (container) {
          container.insertBefore(widget, container.firstChild);
          console.log('Widget créé avec succès');
        } else {
          console.log('Aucun conteneur trouvé pour le widget');
        }
      }
    }
    
    async function updateCheckTimes() {
      try {
        // Créer le widget si nécessaire
        createCheckTimesWidget();
        
        // Calculer les heures basées sur l'intervalle de 5 minutes
        const now = new Date();
        const lastCheck = new Date(now.getTime() - 5 * 60 * 1000);
        const nextCheck = new Date(now.getTime() + 5 * 60 * 1000);
        
        const lastCheckElement = document.getElementById('last-check');
        const nextCheckElement = document.getElementById('next-check');
        
        if (lastCheckElement && nextCheckElement) {
          lastCheckElement.textContent = lastCheck.toLocaleString('fr-FR');
          nextCheckElement.textContent = nextCheck.toLocaleString('fr-FR');
        }
      } catch (error) {
        console.log('Erreur lors de la mise à jour:', error);
      }
    }
    
    // Attendre que la page soit complètement chargée
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', createCheckTimesWidget);
    } else {
      createCheckTimesWidget();
    }
    
    // Mettre à jour toutes les minutes
    setInterval(updateCheckTimes, 60000);
    updateCheckTimes();

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
