# Change these first
owner: pyleglise # Your GitHub organization or username, where this repository lives
repo: upptimeMonitor # The name of this repository

# Note: Les intervalles sont configurés dans les workflows GitHub Actions
# et ne peuvent pas être modifiés via la configuration .upptimerc.yml

sites:
  - name: axialdata Website
    url: https://www.axialdata.net/presentation
    check: "keyword"
    keyword: "A propos de axialdata"
  - name: Portfolio Pierre-Yves Léglise
    url: https://www.axialdata.app/
    check: "keyword"
    keyword: "const userInfo = { Portfolio_v"
  - name : flexiCom frontend
    url: https://flexicom.mondialparebrise.app/
    check: "keyword"
    keyword: "En utilisant flexiCom vous acceptez les conditions générales d'utilisation"
  - name: flexiCom backend
    url: https://flexicom-api.mondialparebrise.app/api/v1/session/by-cookie
    # check: "status"
    # status: 304
    check: "body.byCookieUnavailable"
    body.byCookieUnavailable: true
  - name: axialQuote frontend
    url: https://axialquote.axialdata.app/
    check: "keyword"
    keyword: "Application de calcul de devis axialQuote par axialdata"
  - name: axialQuote backend
    url: https://aq-api.axialdata.app/
    check: "keyword"
    keyword: "This API is strictly reserved for authorized users"
  - name: Intranet Voile Nature
    url: https://intranet.voilenature.com/
    check: "keyword"
    keyword: "Espace collaboratif réservé aux membres Voile Nature"
  - name: Esprit Guitare
    url: https://www.espritguitare.fr/rendez-vous/
    check: "keyword"
    keyword: "Choisissez la date et le créneau horaire"
  - name: Franck Barros
    url: https://barros-music.com/
    check: "keyword"
    keyword: "Politique de"
  - name: Claire Debourg Arbitration
    url: https://www.cdarbitration.com
    check: "keyword"
    keyword: "Claire Debourg Arbitration"
  - name: Vitrail Martinique
    url: https://www.vitrailmartinique.com
    check: "keyword"
    keyword: "Vitrail Martinique"
  - name: Ma Pause Mieux Etre
    url: https://www.mapausemieuxetre.fr
    check: "keyword"
    keyword: "Ma Pause Mieux Etre"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: /upptimeMonitor
  logoUrl: https://www.axialdata.net/wp-content/uploads/2022/07/Logo-carre-AxialData-v2.jpg
  name: "Moniteur de Statut - axialdata"
  introTitle: "**Surveillance axialdata**"
  introMessage: "Surveillance en temps réel des services de axialdata"
  navbar:
    - title: Status
      href: /upptimeMonitor/
    - title: Force Check
      href: https://github.com/$OWNER/$REPO/actions/workflows/uptime.yml
    - title: axialdata
      href: https://www.axialdata.net
  # Widget personnalisé pour afficher les heures de vérification
  customBodyHtml: |
    <div id="check-times-widget" class="check-times">
      <p><strong>Dernière vérification :</strong> <span id="last-check">Calcul en cours...</span>             <strong>Prochaine vérification :</strong> <span id="next-check">Calcul en cours...</span></p>
    </div>
  links:
    - rel: stylesheet
      href: https://pyleglise.github.io/upptimeMonitor/custom.css
  scripts:
    - src: https://pyleglise.github.io/upptimeMonitor/custom.js

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
