# Change these first
owner: pyleglise # Your GitHub organization or username, where this repository lives
repo: upptimeMonitor # The name of this repository

sites:
  - name: axialdata
    url: https://www.axialdata.net/presentation
    check: "keyword"
    keyword: "A propos de axialdata"
  - name: CFF to PDF API via Fly.io
    url: https://cff-to-pdf-api.fly.dev/api/v2/webhook/connect
    check: "keyword"
    keyword: "Authorized users only"
  - name: Claire Debourg Arbitration
    url: https://www.cdarbitration.com
  - name: Vitrail Martinique
    url: https://www.vitrailmartinique.com
  - name: Ma Pause Mieux Etre
    url: https://www.mapausemieuxetre.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptimeMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Moniteur de Statut"
  introTitle: "**Surveillance axialdata**"
  introMessage: "Surveillance en temps réel des services de axialdata"
  navbar:
    - title: Status
      href: /upptimeMonitor/
    - title: axialdata
      href: https://www.axialdata.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
